[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/']
optimizer_runs = 1000000

# while this reduces gas for this contract, its still a bit iffy for regular solidity
viaIR = false

# See more config options https://github.com/gakonst/foundry/tree/master/config