[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/']
fuzz_runs = 1
optimizer_runs = 1000000

# while this reduces gas for this contract, its still a bit iffy for regular solidity
viaIR = false

[ci]
fuzz_runs = 10000

# See more config options https://github.com/gakonst/foundry/tree/master/config